### ISSUE TITLE
Cannot use clear in middleware

### ISSUE THREAD

**Issue by bitbytebit1** [Atinux/nuxt-auth-utils#63]
I have a global middleware that looks something like this.

```
const { loggedIn, user, clear } = useUserSession()

// If user is logged in but permissions are not loaded, then force the user to re-login
if (loggedIn?.value && !user?.value?.permissions) {
  await clear()
  return navigateTo(`/login`)
}
```

Calling the clear method during SSR results in the following error.

```
Feb 26 14:27:09 xxx.com node[152599]: Error clearing user session Error: [nuxt] instance unavailable
Feb 26 14:27:09 xxx.com node[152599]: at useNuxtApp (file:///xxx/.output/server/chunks/app/server.mjs:1503:13)
Feb 26 14:27:09 xxx.com node[152599]: at useState (file:///xxx/.output/server/chunks/app/server.mjs:2104:35)
Feb 26 14:27:09 xxx.com node[152599]: at useSessionState (file:///xxx/.output/server/chunks/app/server.mjs:2140:31)
Feb 26 14:27:09 xxx.com node[152599]: at clear (file:///xxx/.output/server/chunks/app/server.mjs:2160:3)
Feb 26 14:27:09 xxx.com node[152599]: at async file:///xxx/.output/server/chunks/app/server.mjs:2191:59
Feb 26 14:27:09 xxx.com node[152599]: at async Object.callAsync (file:///xxx/.output/server/chunks/app/server.mjs:90:16)
Feb 26 14:27:09 xxx.com node[152599]: at async file:///xxx/.output/server/chunks/app/server.mjs:2336:26
```

**Comment by Atinux** [comment]
What about using a hook instead to always fill the permissions when you get the session on client-side?

https://github.com/Atinux/nuxt-auth-utils?tab=readme-ov-file#extend-session

**Comment by colinmollenhour** [comment]
@atinux I tried this but got the error "useState is not defined" and if I add an import for "nuxt/app" the server won't even start.. Can you provide an example how I can call useState whenever the session is cleared?

`server/plugins/session.ts`
```
export default defineNitroPlugin((nitro) => {
    sessionHooks.hook('clear', async (session, event) => {
        console.log('User logged out: ' + session.user?.id)
        useState('teams').value = []  // throw 'useState is not defined'
    })
})
```
